#pragma once

#include <PinNames.h>

#define MOTORS 5

#define MOTOR_PP 5
#define VOLTAGE_POWER_SUPPLY 9
#define VOLTAGE_SENSOR_ALIGN 3
#define VELOCITY_INDEX_SEARCH 3

#define PIN_U_M1    D10 // PK1_ALT1
#define PIN_V_M1    D1  // PA9_ALT1
#define PIN_W_M1    D57 // PJ9_ALT1

#define PIN_U_M2    D85 // PA5
#define PIN_V_M2    D66 // PA1
#define PIN_W_M2    D3  // PA2

#define PIN_U_M3    D7  // PB4
#define PIN_V_M3    D5  // PA7_ALT1
#define PIN_W_M3    A2  // PB0_ALT1

#define PIN_U_M4    D6  // PD13
#define PIN_V_M4    D8  // PB8
#define PIN_W_M4    D9  // PB9

#define PIN_U_M5    D4  // PJ8_ALT1
#define PIN_V_M5    D15 // PC7_ALT1
#define PIN_W_M5    D48 // PK0_ALT1

#define PIN_EN_M1   D2
#define PIN_EN_M2   D14
#define PIN_EN_M3   D0
#define PIN_EN_M4   D16
#define PIN_EN_M5   D17

#define PIN_MAG_CS1 D56
#define PIN_MAG_CS2 D58
#define PIN_MAG_CS3 D60
#define PIN_MAG_CS4 D62
#define PIN_MAG_CS5 D64

#define PIN_SENSE_M1 A5
#define PIN_SENSE_M2 A4
#define PIN_SENSE_M3 A3
#define PIN_SENSE_M4 A1
#define PIN_SENSE_M5 A0

#define PIN_FAULT_M1 D94
#define PIN_FAULT_M2 D93
#define PIN_FAULT_M3 D84
#define PIN_FAULT_M4 A7
#define PIN_FAULT_M5 A6

// SPI1
#define PIN_SPI_MOSI D11
#define PIN_SPI_MISO D12
#define PIN_SPI_SCK  D13

#define PIN_LED D88

#define PK_1_ALT1 (PinName)(PK_1 | ALT1) // TIM1_CH1
#define PA_9_ALT1 (PinName)(PA_9 | ALT1) // TIM1_CH2
#define PJ_9_ALT1 (PinName)(PJ_9 | ALT1) // TIM1_CH3

#define PJ_8_ALT1 (PinName)(PJ_8 | ALT1) // TIM8_CH1 alt: PI_5_ALT3 / D54
#define PC_7_ALT1 (PinName)(PC_7 | ALT1) // TIM8_CH2 alt: PI_6_ALT3 / D59
#define PK_0_ALT1 (PinName)(PK_0 | ALT1) // TIM8_CH3 alt: PI_7_ALT3 / D58

const PinMap PinMap_TIM[] = {
  { PK_1_ALT1, TIM1_BASE,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF1_TIM1, 1, 0)}, // TIM1_CH1
  { PA_9_ALT1, TIM1_BASE,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF1_TIM1, 2, 0)}, // TIM1_CH2
  { PJ_9_ALT1, TIM1_BASE,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF1_TIM1, 3, 0)}, // TIM1_CH3

  { PA_5,      TIM2_BASE,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF1_TIM2, 1, 0)}, // TIM2_CH1
  { PA_1,      TIM2_BASE,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF1_TIM2, 2, 0)}, // TIM2_CH2
  { PA_2,      TIM2_BASE,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF1_TIM2, 3, 0)}, // TIM2_CH3

  { PB_4,      TIM3_BASE,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF2_TIM3, 1, 0)}, // TIM3_CH1
  { PA_7_ALT1, TIM3_BASE,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF2_TIM3, 2, 0)}, // TIM3_CH2
  { PB_0_ALT1, TIM3_BASE,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF2_TIM3, 3, 0)}, // TIM3_CH3

  { PD_13,     TIM4_BASE,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF2_TIM4, 2, 0)}, // TIM4_CH2
  { PB_8,      TIM4_BASE,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF2_TIM4, 3, 0)}, // TIM4_CH3
  { PB_9,      TIM4_BASE,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF2_TIM4, 4, 0)}, // TIM4_CH4

  { PJ_8_ALT1, TIM8_BASE,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF3_TIM8, 1, 0)}, // TIM8_CH1
  { PC_7_ALT1, TIM8_BASE,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF3_TIM8, 2, 0)}, // TIM8_CH2
  { PK_0_ALT1, TIM8_BASE,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF3_TIM8, 3, 0)}, // TIM8_CH3
};
